// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuAVBRtEbxx-rgbTFeNRZ2slkF0v6V98k',
    appId: '1:396040856822:android:ba613b10a016a7e484f8d7',
    messagingSenderId: '396040856822',
    projectId: 'buudi-67949',
    storageBucket: 'buudi-67949.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSafYYTDasENC6mWzSkNzBHulYNgjDQZw',
    appId: '1:396040856822:ios:77bbbfef7309d76584f8d7',
    messagingSenderId: '396040856822',
    projectId: 'buudi-67949',
    storageBucket: 'buudi-67949.appspot.com',
    iosClientId: '396040856822-tbdt26mi8q9ld6tl10ko4tjfjqu3cj2r.apps.googleusercontent.com',
    iosBundleId: 'com.buudiafrica.mobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwYoSbxvopW83_s2bYCF4OSAhKQ1K_U4s',
    appId: '1:396040856822:web:006947f1497defa884f8d7',
    messagingSenderId: '396040856822',
    projectId: 'buudi-67949',
    authDomain: 'buudi-67949.firebaseapp.com',
    storageBucket: 'buudi-67949.appspot.com',
    measurementId: 'G-3L22ZDD8Y7',
  );

}